GET http://localhost:3000/v1/user/esteban HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoiZXN0ZWJhbiIsInBhc3N3b3JkIjoicGFzcyJ9LCJpYXQiOjE2NTM2ODcwMTUsImV4cCI6MTY1MzY4NzA3NX0.Rh4NQbT_sw1awqHlcddhTaXXNtlFGUMGKjNVaStwfQ9Z2yJQvpN_T2_EQDdelbYrAYqg8TSnNfGDpFyTXpZfU8P0TVRprYCBf5LYF4BGaCxzQLpFMHqkXC35Gzq0Zki6bS8ngUEckIYyLgvOsZJAcNowAf1ve_7XY1tDbhY7K_oYN6rpItAqwGrunQvejN_8HIsi3DLAU0ome0zjymUyfdw_0wnY6q4WaAN3BiOXGSB1WQzkI6FxR8Wno_5Wa7bzEQadksfF_E0xyPeQfn1MlvtpOtx28bZf2zu70835iImDopRfkZx_iyC6PozivyUi1rekBzPZlvrTJBGKzS55RQ